[package]
name = "tau-memory"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Internal crates

tau-contract = { path = "../tau-contract" }

[dev-dependencies]
tempfile = "3.25"
