[package]
name = "tau-trainer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tau-training-runner = { path = "../tau-training-runner" }
tau-training-store = { path = "../tau-training-store" }
tau-training-types = { path = "../tau-training-types" }

[dev-dependencies]
tau-training-tracer = { path = "../tau-training-tracer" }
